### PR TITLE
Add support for Laravel 9

### PR DESCRIPTION
**Pull request by phpfour**
Tested with the latest version of Laravel 9.

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@phpfour Thanks for this, are you able to update the GitHub workflows too?

**Comment by phpfour** [comment]
@ryangjchandler sure, let me take a look.

**Comment by ryangjchandler** [comment]
@phpfour Why do we need `^8.0|^8.1` - `^8.0` means `>= 8.0.0 && < 9.0` so should cover both.

**Comment by phpfour** [comment]
@ryangjchandler my bad with the PHP version change, I've reverted it. 

I have updated the `illuminate/contracts` to the latest version as it was failing on PHP 8.1 (related to `symfony/http-foundation` not being up to date). Let me know if that's okay.

**Pull request merged**
